#!/usr/bin/env bash
# Archon registry emitters: generate the registry JSON from descriptors, policies, and the
# .agents/ navigation layer. Sourced after common.sh + descriptor.sh (uses jq).
# Output is compact (one record per line, like tools.json) so RTK + jq stay cheap.

_archon_now() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# Join a compact JSON array into a single inline `a,b,c` string (empty if no elements).
_archon_inline() { jq -c '.[]' <<<"$1" | paste -sd, -; }

# units.json — colocated-first discovery, central overrides colocated for a shared id.
archon_emit_units() {
  local units='[]' f src full id rec
  local -A from_central=()
  while IFS=$'\037' read -r f src; do
    [ -n "$f" ] || continue
    full="$(archon_descriptor_json "$f")"
    id="$(jq -r '.id' <<<"$full")"
    rec="$(archon_unit_record "$full" "$src")"
    if [ "$src" = "central" ]; then
      from_central[$id]=1
    elif [ -n "${from_central[$id]:-}" ]; then
      continue   # central already won for this id
    fi
    units="$(jq -c --argjson r "$rec" 'map(select(.id != $r.id)) + [$r]' <<<"$units")"
  done < <(archon_find_descriptors)

  units="$(jq -c 'sort_by(.id)' <<<"$units")"
  local summary inline
  summary="$(jq -c '{
    total: length,
    by_kind: (group_by(.kind) | map({key: .[0].kind, value: length}) | from_entries)
  }' <<<"$units")"
  inline="$(_archon_inline "$units")"
  printf '{\n  "generated_at": "%s",\n  "summary": %s,\n  "units": [%s]\n}\n' \
    "$(_archon_now)" "$summary" "$inline"
}

# policies.json — index every policy TOML (parsed via the descriptor reader) with its source.
archon_emit_policies() {
  local arr='[]' f full rel
  for f in "$ARCHON_POLICIES"/*.toml; do
    [ -e "$f" ] || continue
    full="$(archon_descriptor_json "$f")"
    rel="${f#"$WS_ROOT"/}"
    arr="$(jq -c --argjson p "$full" --arg src "$rel" '. + [$p + {source: $src}]' <<<"$arr")"
  done
  printf '{\n  "generated_at": "%s",\n  "policies": [%s]\n}\n' \
    "$(_archon_now)" "$(_archon_inline "$arr")"
}

# skills.json — populated by E06 from .agents/skills/. Emits any *.toml skill descriptors
# present today (none yet → empty array).
archon_emit_skills() {
  local arr='[]' f full
  if [ -d "$AGENTS_HOME/skills" ]; then
    for f in "$AGENTS_HOME"/skills/*.toml; do
      [ -e "$f" ] || continue
      full="$(archon_descriptor_json "$f")"
      arr="$(jq -c --argjson s "$full" '. + [$s]' <<<"$arr")"
    done
  fi
  printf '{\n  "generated_at": "%s",\n  "skills": [%s]\n}\n' \
    "$(_archon_now)" "$(_archon_inline "$arr")"
}

# local-toolkit.yml — the .agents/ navigation view of the toolkit, derived from the Dust
# manifest + tools.json. Each tool gets one mutually-exclusive status:
#   present   = installed on this host
#   missing   = a module-default that is absent (should be installed)
#   candidate = an optional tool (default=false) not installed — available to adopt
#   deprecated= flagged for removal (none today; taxonomy slot)
archon_emit_local_toolkit() {
  local tools="$ARCHON_REGISTRY/tools.json"
  [ -f "$tools" ] || { archon_warn "tools.json absent — run 'dust doctor' before sync to emit local-toolkit.yml"; return 1; }
  local classified mver host cp cm cc bucket items
  mver="$(jq -r '.manifest_version' "$tools")"
  host="$(jq -r '.host' "$tools")"
  classified="$(jq -c '.tools | map({id, module, default,
    status: (if .installed then "present" elif .default then "missing" else "candidate" end)})' "$tools")"
  cp=$(jq -r '[.[]|select(.status=="present")]  | length' <<<"$classified")
  cm=$(jq -r '[.[]|select(.status=="missing")]  | length' <<<"$classified")
  cc=$(jq -r '[.[]|select(.status=="candidate")]| length' <<<"$classified")

  printf '# GENERATED by `archon sync` from the Dust manifest + archon/registry/tools.json.\n'
  printf '# Do not hand-edit — regenerate with `moon run archon:sync`. Host-specific (gitignored).\n'
  printf 'generated_at: "%s"\n' "$(_archon_now)"
  printf 'manifest_version: "%s"\n' "$mver"
  printf 'host: "%s"\n' "$host"
  printf 'summary: { present: %s, missing: %s, candidate: %s, deprecated: 0 }\n' "$cp" "$cm" "$cc"
  for bucket in present missing candidate deprecated; do
    items="$(jq -r --arg s "$bucket" \
      '[.[]|select(.status==$s)] | sort_by(.id) | .[] | "  - { id: \(.id), module: \(.module), default: \(.default) }"' \
      <<<"$classified")"
    if [ -n "$items" ]; then printf '%s:\n%s\n' "$bucket" "$items"; else printf '%s: []\n' "$bucket"; fi
  done
}

# graph.json — the project relationship graph, derived from units.json + policies.json.
# Nodes: units (kind from descriptor), capabilities (capability:<name>), policies
# (policy:<id>), and an actor node ("agent") when a policy applies_to="agent".
# Edges: unit -provides-> capability, unit -requires-> capability,
#        unit -uses-> unit (when requires∩provides across units),
#        unit -governed-> policy (when policy.applies_to == unit.id),
#        agent -blocked-by-> policy (when policy.applies_to == "agent").
archon_emit_graph() {
  local units="$ARCHON_REGISTRY/units.json"
  local policies="$ARCHON_REGISTRY/policies.json"
  local profiles="$ARCHON_REGISTRY/profiles.json"
  [ -f "$units" ]   || { archon_warn "units.json absent — graph requires sync to run first"; return 1; }
  [ -f "$policies" ] || { archon_warn "policies.json absent — graph requires sync to run first"; return 1; }
  [ -f "$profiles" ] || printf '{"profiles":[]}' > "$profiles"

  jq -n --arg ts "$(_archon_now)" --slurpfile U "$units" --slurpfile P "$policies" --slurpfile PR "$profiles" '
    ($U[0].units)    as $units    |
    ($P[0].policies) as $policies |
    (($PR[0].profiles) // []) as $profiles |
    ($units | map(. as $u | (.provides // [])[] | {from: $u.id, rel: "provides", to: ("capability:" + .)}))
      as $provides_edges |
    ($units | map(. as $u | (.requires // [])[] | {from: $u.id, rel: "requires", to: ("capability:" + .)}))
      as $requires_edges |
    ([ $units[] as $u | $units[] as $v |
      select($u.id != $v.id) |
      select(
        ($u.requires // []) as $reqs | ($v.provides // []) as $provs |
        any($reqs[]; . as $r | $provs | index($r))
      ) | {from: $u.id, rel: "uses", to: $v.id} ])
      as $uses_edges |
    ($units | map(. as $u | ($policies | map(select(.applies_to == $u.id)) | .[] |
               {from: $u.id, rel: "governed-by", to: ("policy:" + .id)})))
      as $governed_edges |
    [($policies | map(select(.applies_to == "agent")) | .[] |
               {from: "agent", rel: "blocked-by", to: ("policy:" + .id)})]
      as $blocked_edges |
    ([$policies[].id] | unique) as $policy_ids |
    ($profiles | map(. as $pr | select(($pr.rails // null) != null and ($policy_ids | index($pr.rails))) |
               {from: ("profile:" + $pr.id), rel: "selects", to: ("policy:" + $pr.rails)}))
      as $selects_edges |
    ($units | map({id: .id, kind: .kind})) as $unit_nodes |
    (($provides_edges + $requires_edges | map(.to) | unique) | map({id: ., kind: "capability"}))
      as $cap_nodes |
    ($policies | map({id: ("policy:" + .id), kind: "policy"})) as $policy_nodes |
    (if ($blocked_edges | length) > 0 then [{id: "agent", kind: "actor"}] else [] end)
      as $actor_nodes |
    ($profiles | map({id: ("profile:" + .id), kind: "profile"})) as $profile_nodes |
    {
      generated_at: $ts,
      nodes: ($unit_nodes + $cap_nodes + $policy_nodes + $actor_nodes + $profile_nodes),
      edges: ($provides_edges + $requires_edges + $uses_edges + $governed_edges + $blocked_edges + $selects_edges)
    }
  '
}

# graph.dot — Graphviz DOT rendering, derived from graph.json (read from stdin).
archon_emit_graph_dot() {
  jq -r '"digraph archon {\n  rankdir=LR;\n  node [shape=box];\n",
         (.edges[] | "  \"\(.from)\" -> \"\(.to)\" [label=\"\(.rel)\"];\n"),
         "}\n"'
}

# Project a full profile JSON (nested TOML tables) into a compact registry record using the
# exact field names the epic contract declares. Mirrors archon_unit_record.
# Args: <full-json>
archon_profile_record() {
  jq -c '{
    id, title, purpose,
    rails: (.rails // null),
    allowed_paths: (.scope.allowed_paths // []),
    blocked_paths: (.scope.blocked_paths // []),
    allowed_commands: (.commands.allowed_commands // []),
    gated_commands: (.commands.gated_commands // []),
    blocked_commands: (.commands.blocked_commands // []),
    secret_access: (.policy.secret_access // false),
    remote_write_policy: (.policy.remote_write_policy // "blocked"),
    loads_external_skills: (.skills.loads_external // false),
    required_validators: (.validators.required_validators // []),
    output_compressor: (.output.compressor // null),
    session_log_target: (.logs.session_log_target // null)
  }' <<<"$1"
}

# profiles.json — populated by E05 from .agents/profiles/*.toml. Each profile is read by the
# Archon TOML reader and flattened by archon_profile_record into a compact record.
archon_emit_profiles() {
  local arr='[]' f full rec
  if [ -d "$AGENTS_HOME/profiles" ]; then
    for f in "$AGENTS_HOME"/profiles/*.toml; do
      [ -e "$f" ] || continue
      full="$(archon_descriptor_json "$f")"
      rec="$(archon_profile_record "$full")"
      arr="$(jq -c --argjson p "$rec" '. + [$p]' <<<"$arr")"
    done
  fi
  printf '{\n  "generated_at": "%s",\n  "profiles": [%s]\n}\n' \
    "$(_archon_now)" "$(_archon_inline "$arr")"
}
