#ENC[AES256_GCM,data:kvL0YBj7mte6glF4WMwyvJDR7DEt7PQclcEZ4TQFhvQo7t5NHJuEJp+Zzyfjd2vdXYa+QHxI+m692JX4rd+WSXHajxf/Mg==,iv:QUutRz7hlgQ+iiEDLlX/ztwy29KlNAK3eloViiMamW0=,tag:LDmnOAbtrUEirGdGS/8sxQ==,type:comment]
#ENC[AES256_GCM,data:nlvqrMHYvtjVa0xseuujoVYIEjQgo/xBgyZCE+k2ZckTj8ON+k99pon9DCiRz8LF0kcq8KvI0Tm5LFx75hNchxcsctNFneuTf3dPkBZ8DR7KNbTau9cUH+FS4/R6vg==,iv:9J858BK4W9SL8lMZNjIZ37+JZaIAo+nh4cdw5k53rpQ=,tag:bXY1MW0fYqWJvj5X053U8A==,type:comment]
#ENC[AES256_GCM,data:HBHSg74MHNA/6eIv+gtfjIseOr/G2UCp0Mif4iD+aTw8nOi0VbXVHmalRdOOt8cVJHFQOkAu/zey+kjZWrbZjYUGGRasRu48gWpkCrTN/H5Nu36B3eK0JMuf+4vX,iv:yhQ3upzzFjWW13UZFiOI3/+rUzWalAcqO60zLV/ev2M=,tag:99q0oFY6lp55l2k9J8PCYw==,type:comment]
#ENC[AES256_GCM,data:AdkhcAzSRyMklEqWvg4h8AYDH1sZ6mpJlozE04TSDYwQa+8fGEKu+RnUXaosrIT+PVryWU5EN9mv2UULdDG2BJrcSR7Dyh87g511TYZymnG8yE9sZBjjZRVD9ujr,iv:l+Hkq7Tzlv6DYNktoxSSWjgQn01eNUhXy3K9e8Gkg7I=,tag:UlFv5mQapV5uhoc1e1uM8w==,type:comment]
service:
    name: ENC[AES256_GCM,data:tmBk4caYIA==,iv:U874Tf42v/JC6c6TMrZo4W3JTMrrFrVE6iohvOpQ5fE=,tag:jjrJbyLA9wsy9Gg4MUxzPQ==,type:str]
    endpoint: ENC[AES256_GCM,data:L1jB604bfpvZCaJpMU6bGiMHGIuP3G5K,iv:fie3I1o6x7ovt6q8UGqfyeHYTAOqHY8e1YVHCh0Jw5M=,tag:Tc+f6FtsZba/IpS9BJ78rw==,type:str]
secrets:
    api_key: ENC[AES256_GCM,data:vF+sJgx7eNLYsTSzomRUAQ==,iv:UoQ9+y52I+hLNFU6eX8d7N10e7/FZ69q+qKzylhPhlM=,tag:lfTPz5NkA0L0S2m2RWJf+g==,type:str]
    webhook_token: ENC[AES256_GCM,data:so7LOJiE1nLLIjbmVnTzww==,iv:jI4clya5Ayd4heS7Xvwa2HR89Qq4HQ33MS7o1U1uJ3E=,tag:5P7QjO7EAQ4ZWcqK/6zCUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYyttZk0xVU1HUHd0MHZk
            aTFDNzgxNkNWMTBPVDNyV05HNTFWR1RZMkJZClJuckpqRE1xcnF3WHYyL0t1ZjM2
            QVluaWpUTm16U3JLOExWeVloNnhuRTQKLS0tIEtkN0Z6MzhUUGE4VFRGRFVJSXBp
            aUs2SHQwWXoyY0JJRXp3MCsxaWxhY1UK2iw4WEXO37cs57/MJ4CAXo7gavrPyODa
            EZUqt2SmW9UoP1DdmjgrUg+ZaTAazfgrFtjkJi46cIPh3mLwBn44bQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sypm2y50ryrz80fq70gpavmrgp4wrscru8zz9v6yuats4rc393sq54ftfs
    lastmodified: "2026-06-24T01:43:49Z"
    mac: ENC[AES256_GCM,data:KCeoszlhCXRfO+BDrWxhC7kU6ddy1uYYTmmcBOv2365sjuusnNmx499zDTmPGH7sa52NYLN1ii/yesg4n2YuOAUyEWvlsxRbvYK1Vd1uKJzokYJmNbcNX65kL+7e+PDxxdVnh0PSO7cDx2dVYftDONiHZ8gfutQdU6ADzbMC4CU=,iv:cPKoGHSldsmNL8J5YUBAqPCR/c/YyMhP2EoAtp0Qkxw=,tag:cxXOd8Aa+0JZwYAmeBu9ew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
